### ISSUE TITLE
Disappearing names (to unnamed)

### ISSUE THREAD

**Issue by mayasfinest** [ElliotGarbus/Hedra-Editor-and-librarian#2] opened 2021-08-21 23:31 UTC
Hi Elliot,

i have your Mercury7,Polymoon,Hedra and Enzo Editors in upcoming use and try to dig in the functionality of your editors and build up a library for me. So enormous helpful, i love them very much so far.
I communicate with the Pedals via Meris I/O and a Roland UM-One. And I use an Audiofront MIDI Expression iO for Expression-Pedal-Input; works like a charm so far.... 
However, when I work in the Hedra Editor, make my 16 Presets and transfer them to the Hedra, the names of the presets in the list seem to disappear (one by one) and being swapped out by the name of 'unnamed'. When I save them as a preset group, they also get he same unnamed label after I load them up again. Sometimes a (or some) real-name appears, not always the same ones. The presets are in the right location and work as expected. I opened the Groupfile.pgr in a Text-editor, all names are stored correctly.
Sometimes (rarely) this also happens in the other editors; a name disappears and gehts swapped out by unnamed - but with the Hedra editor this happens with every preset....

Do you have any ideas?

**Comment by ElliotGarbus** [comment] 2021-08-21 23:55
What version of the editor are you using?  Please make sure you are using version 3.0.  You can check there version, by going to the Help menu and selecting About.  Version 3.0 added the patch generator to Hedra.

If you are already running 3.0 let me know if you are Windows or Mac, and if you are on Mac, what version of MacOS.  I just ran a few test on Windows and can not reproduce the issue. 

The problem you are describing suggests data is not coming back from the pedal correctly.  Make sure the TRS cable is firmly in the exp socket and the MIDI I/O and that the midi Jack are firmly seated in the MIDI I/O.  You can also try turning the knobs on the pedal, they should turn on the screen.

I have seen some timing sensitives with some of the pedals, usually with devices other than the MIDI I/O.  I did slow down the midi communication in version 3.0.  
Is the UM-One connected directly to a USB port on the computer, or through a USB hub?  If you are using a hub, try connecting directly to the computer.

I look forward to hearing back from you and working to get this issue resolved.

**Comment by mayasfinest** [comment] 2021-08-23 11:50
> What version of the editor are you using? Please make sure you are using version 3.0. You can check there version, by going to the Help menu and selecting About. Version 3.0 added the patch generator to Hedra.
> 
> If you are already running 3.0 let me know if you are Windows or Mac, and if you are on Mac, what version of MacOS. I just ran a few test on Windows and can not reproduce the issue.
> 
> The problem you are describing suggests data is not coming back from the pedal correctly. Make sure the TRS cable is firmly in the exp socket and the MIDI I/O and that the midi Jack are firmly seated in the MIDI I/O. You can also try turning the knobs on the pedal, they should turn on the screen.
> 
> I have seen some timing sensitives with some of the pedals, usually with devices other than the MIDI I/O. I did slow down the midi communication in version 3.0.
> Is the UM-One connected directly to a USB port on the computer, or through a USB hub? If you are using a hub, try connecting directly to the computer.
> 
> I look forward to hearing back from you and working to get this issue resolved.

Thanks Elliot, very helpful hints to look at.

OK, here's more details:
I am on a Win10 tablet running your 3.0. As i only have one USB port i use a passive hub (rather old) to have the UM-one and the Audiofront both connected, otherwise i have no Expression-pedal-input.
I tried swapping out the passive hub with an active one (also rather old), no real difference in behaviour, except that 2 names of the 16 appeared and the others "unnamed" and these are always the same 2... But when i tried out different port combinations, they also come and go.
There is full-duplex communication on the USB-side, i see knobs moving when touching the hardware, but maybe it's too slow...?
All your other editors work fine, but rarely there are also names disappearing. The patch always works, no matter what name there is, also the expression pedal movements, but it is annoying to not know what preset it is.
Furthermore, when starting-up the editor, the software reads out Hedras memory, this takes about 20-25 sec. ... is this alright? The same with the other editors, somehow slow for this few data.

Thanks a lot,
Greetings from Germany
Jörg

Addendum:
I just tried all your other Meris editors and it is Hedra and Mercury7 being much more slower (three times longer) when reading out the pedals memory than Polymoon and Enzo. And Mercury7 also has rare "unnamed" issues, but only with one or two names missing...
I also tried one more hub (active USB3); i think i felt a little speeding up in reading-out but this is rather unnoticeable and Hedras-Editors name are still all named "unnamed"

**Comment by ElliotGarbus** [comment] 2021-08-23 12:58
Interesting.  Does the editor work properly if you connect the UM-One directly to the computer, without the hub?
25 seconds sounds too long for loading the presets, I'll time it later today.

FYI There is no timing spec for midi.  The Meris pedals require a delay in between messages or data is lost.  Some pedals require more delay than others (M7 required the most).  I extended this delay in the Hedra in version 3.0 because a user was reporting occasional 'unnamed' patches.  

I suspect the issue is caused by the hub having an effect on the programmed delays between the transmitted midi messages.  I see if I can find a hub (i know i have at least one...) and see if I can reproduce the issue.

**Comment by mayasfinest** [comment] 2021-08-23 20:59
I tried some constellations: (all with no difference) but in the most basic one
"Direct connection of UM-One straight to the Meris I/O with no hub involved" there is also no change in behaviour.

Maybe it's a tablet thing? Too slow in Midi-USB-communication? 
But i havent't had any speed issues with none of your editors regarding screen response and except the Hedra-editor i don't have this (very rare) "unnamed" issue in the others.

Could you increase this midi message delay furthermore or does it slow down other parameters?

**Comment by ElliotGarbus** [comment] 2021-08-23 22:30
Can you try with your table plugged into power?  (assuming you have been running it on battery). 

I'll take a look at creating a custom version for you that lets you set the inter-message delay time.  I should be able to get to it in the next few weeks.  We can then do some tests to see if that fixes the issue.    The only obvious issue you will see that on startup it will take longer to load the presets from the pedal.

**Comment by mayasfinest** [comment] 2021-08-23 22:51
No, it already runs on mains (battery died some months ago).
It would be very nice to have the delay tweakable. Maybe you could just code an exaggerated version first to see if it really fixes the issue. I have no idea how complicated it is, so excuse my word "just" ;-)
Many thanks for your efforts in advance.

**Comment by ElliotGarbus** [comment] 2021-08-24 00:26
There might be an hint as to what is going on in the log file.  Load the Hedra app, use it so you see the failure.  Then close the app and go the the following directory:   C:\Users\YourUserName\\.kivy\logs
Find the most recent log file and post it.  It is a text file you can read through it, I'm hoping to see an error that will provide some insight into the issue.

**Comment by mayasfinest** [comment] 2021-08-24 06:24
[INFO   ] Logger: Record log in C:\Users\Lenovo Tab\.kivy\logs\kivy_21-08-24_5.txt
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "C:\Program Files\Hedra Editor and Librarian\kivy\__init__.pyc"
[INFO   ] Python: v3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
[INFO   ] Python: Interpreter at "C:\Program Files\Hedra Editor and Librarian\HedraEdit.exe"
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: GLEW initialization succeeded
[INFO   ] GL: Backend used <glew>
[INFO   ] GL: OpenGL version <b'4.0.0 - Build 10.18.10.4491'>
[INFO   ] GL: OpenGL vendor <b'Intel'>
[INFO   ] GL: OpenGL renderer <b'Intel(R) HD Graphics'>
[INFO   ] GL: OpenGL parsed version: 4, 0
[INFO   ] GL: Shading version <b'4.00 - Build 10.18.10.4491'>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] GL: NPOT texture support is available
[WARNING] Both Window.minimum_width and Window.minimum_height must be bigger than 0 for the size restriction to take effect.
[INFO   ] Base: Start application main loop

**Comment by mayasfinest** [comment] 2021-08-24 06:27
![image](https://user-images.githubusercontent.com/73408297/130567041-4a3cdecc-e662-4e56-87e0-fcf32a1dfd37.jpeg)

**Comment by ElliotGarbus** [comment] 2021-08-24 15:07
Looking at the log, I don't see any errors.  It also appears the app was not closed.  I would expect to see a line about the app closing.  Can you please try again, and close the app before grabbing the log.  I would expect the last line to be:
[INFO   ] Base: Leaving application in progress...

Are there patches in the library and do the patches on the device match what is in the library?
If you drag a patch from the library onto a preset button, what happens?  Does the name change on the preset button?  Does the sound play correctly?  If you restart after dragging a patch onto the preset do you see it show up correctly - or do you see 'Unnamed'.
Also try selecting an unnamed patch, then save it.  I would expect to see an error if the patch is in the library.

**Comment by mayasfinest** [comment] 2021-08-24 17:56
[INFO   ] Logger: Record log in C:\Users\Lenovo Tab\.kivy\logs\kivy_21-08-24_32.txt
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "C:\Program Files\Hedra Editor and Librarian\kivy\__init__.pyc"
[INFO   ] Python: v3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
[INFO   ] Python: Interpreter at "C:\Program Files\Hedra Editor and Librarian\HedraEdit.exe"
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: GLEW initialization succeeded
[INFO   ] GL: Backend used <glew>
[INFO   ] GL: OpenGL version <b'4.0.0 - Build 10.18.10.4491'>
[INFO   ] GL: OpenGL vendor <b'Intel'>
[INFO   ] GL: OpenGL renderer <b'Intel(R) HD Graphics'>
[INFO   ] GL: OpenGL parsed version: 4, 0
[INFO   ] GL: Shading version <b'4.00 - Build 10.18.10.4491'>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] GL: NPOT texture support is available
[WARNING] Both Window.minimum_width and Window.minimum_height must be bigger than 0 for the size restriction to take effect.
[INFO   ] Base: Start application main loop
[INFO   ] WindowSDL: exiting mainloop and closing.
[INFO   ] Base: Leaving application in progress...

**Comment by mayasfinest** [comment] 2021-08-24 18:11
> Looking at the log, I don't see any errors. It also appears the app was not closed. I would expect to see a line about the app closing. Can you please try again, and close the app before grabbing the log. I would expect the last line to be:
> [INFO ] Base: Leaving application in progress...
> 


> Are there patches in the library and do the patches on the device match what is in the library?

The library was left almost default (after the Hedra editor setup). As i just started fiddling around with your editor i firstly used the ones marked "Factory preset", kept the original order untouched and tweaked my way from there using you new "Save to Hedra & Lib" function. Then I had a selection of 16 slightly tweaked presets, and saved them as a "Preset Group". When I open this *.grp file in a text editor it correctly shows all the patches. When i load this *.grp file and upload it to Hedra it's the same as reading out Hedras memory - some names appear randomly (in case of the log above there were 7 patches loaded correctly) the others are marked "unnamed" - but all seem to work correctly, it's just the name that disappeared.

> If you drag a patch from the library onto a preset button, what happens? 

This works just fine, the name gets updated, the patch gets uploaded and works as expected. But when i save this new constellation as a preset group and load it up again, it's resolves in just the same "unnamed" behaviour.

Does the name change on the preset button? 
Yes

Does the sound play correctly? 
Yes 

If you restart after dragging a patch onto the preset do you see it show up correctly - or do you see 'Unnamed'.

see above

> Also try selecting an unnamed patch, then save it. I would expect to see an error if the patch is in the library.

see my next post with a screenshot

**Comment by mayasfinest** [comment] 2021-08-24 18:14
![image](https://user-images.githubusercontent.com/73408297/130668415-fdfb5653-f4e7-4acd-a0fa-4d26d1a9910f.jpeg)

This is what opens up when i try to save one of these unnamed presets....

**Comment by mayasfinest** [comment] 2021-08-24 18:54
I just found out, that when i save each and every preset under a new name they keep their name...
I have to try out some more things, to see if this is the way to go (as it it quite time consuming) please wait...

**Comment by ElliotGarbus** [comment] 2021-08-24 19:01
Here is a little background that may help you  make sense of things.
The presets do not store the name in the preset that gets sent to the pedal.  This is how the pedal works.  
The editor looks at the data in the preset, and if there is a match in the library it uses that name.  If the presets on the pedal are not saved in the librarian, they come up Unnamed.  If you were storing changes into the pedal, but not saving them in the librarian – this is what would happen.  I’m surprised that you managed to do that.  The editor does not let you save a patch without giving it a unique name.

How were you saving patches to the pedal?

**Comment by mayasfinest** [comment] 2021-08-24 19:33
> Here is a little background that may help you make sense of things. The presets do not store the name in the preset that gets sent to the pedal. This is how the pedal works. The editor looks at the data in the preset, and if there is a match in the library it uses that name. If the presets on the pedal are not saved in the librarian, they come up Unnamed. If you were storing changes into the pedal, but not saving them in the librarian – this is what would happen. I’m surprised that you managed to do that. The editor does not let you save a patch without giving it a unique name. How were you saving patches to the pedal? 

This "save as new" seems to work, i was able to keep all of the presets names and they are stored and being recalled correctly.
But... when i change something and use your "Update Preset" function i either get an error message telling me "Error: This sound is in the Library as: *name* or if i am able to use it and get to the update button it stores it but i am left with an unnamed preset slot again :-( and have to use my save as method again... very strange

The way i do this save as is as follows:
- drag a preset from the library on a slot named unnamed
- delete that preset immediately from the library
- push the "Save to Hedra&Lib" button and give it a name and store it on the Hedra too

**Comment by mayasfinest** [comment] 2021-08-24 19:46
Another weird behaviour:
If i change one of my newly created presets that are now "permanent" and use "Save to Hedra&Lib" instead of "Update Preset", give it a new name and replace it in Hedras preset slot, then i get an "unnamed" slot again.
When i then drag the newly saved preset again from the library and do this again:
 
"
- drag a preset from the library on a slot named unnamed
- delete that preset immediately from the library
- push the "Save to Hedra&Lib" button and give it a name and store it on the Hedra too
"

it gets stored permanently with the changes

Hope this is understandable in some way...

**Comment by ElliotGarbus** [comment] 2021-08-25 03:31
I will try to recreate the issues you are seeing tomorrow.  
If there was an issue with the midi delay, there should be errors showing up in the log.  It seems like the issue was the patches in the device, did not match the patches in the librarian.

**Comment by ElliotGarbus** [comment] 2021-08-27 03:06
Apologies for the delay, I will be trying to reproduce your issues this weekend.  Have you been able to define a workflow that works for you?

**Comment by mayasfinest** [comment] 2021-08-27 10:26
Hi Eliott,
no, not really.... :-(
I was able to have your editor load Hedra's correct names everytime i start it. 
As far as i don't change anything (saving via the update function) there is no problem.
If i want to change something permanently (save) i'll have to do the following:

- change what i want to change...
- firstly delete the preset from the the library if i want to keep the same name
- push the "Save to Hedra&Lib" button and give it the same name as before and store it on the Hedra too

Then it stays there and loads up correctly everytime i start Hedra+Editor

If i change one of my newly fixed presets and click "Update Preset" then i get an "unnamed" slot again, that stays also permanently "unnamed" unless i do the delete&save process mentionend above again.

And even worse: now i sometimes have this "unnamed" behaviour also in the poly editor (with only a few presets), but i am able to just drag and drop the missing presets from the library again to the unnamed slot and it stays there.

I have all my selections saved as preset group files, but it makes no difference if i load them anew, sometimes names get restored then, but not all...

I also tried the UM-One + Hedra on my big desktopmachine, which is fast and has USB3 ports. There i had similar issues with the Hedra names, but more names got transfered  correctly. But that was before i came up with this delete/save procedure which now works also on my tablet.

I have no clue where the core problem is... and why my freshly stored presets are recalled correctly... all are only text files

**Comment by ElliotGarbus** [comment] 2021-08-27 17:48
I just brought it up.  I am seeing some erroneous behavior.  I'll let you know what I find.

**Comment by ElliotGarbus** [comment] 2021-08-27 18:42
This should fix it.  Please let me know if this addresses your issues.  If if does I will update the release.  Unzip the file and run the executable.  It will launch the normal install.
[HedraEdit_setup.zip](https://github.com/ElliotGarbus/Hedra-Editor-and-librarian/files/7068910/HedraEdit_setup.zip)

**Comment by mayasfinest** [comment] 2021-08-27 21:02
Great! The Update function seems to work now, no more unnamed and the reading from Hedra is almost lightspeed...

Just one issue left :-(

The load Preset Group only imports the first 5 slots. The white progress frame stops at preset nr5.
And if swap a preset past slot 5 with a  different one from the library it doesn't change when i load my saved preset group file.

I don't know what you did inside the code, but there is a slightly similar "unnamed" issue in Polymooon too. And i think i also had it rarely in Mercury7.

**Comment by ElliotGarbus** [comment] 2021-08-27 21:29
I did not see an issue with load preset group.  I'll do some more testing.  
I'll talk a look at ploymoon after the issues are cleared up here.  I suspect a similar issue.  

I had increased the time between transmitted messages on the V3.0 release.  I set it back to where it was, 3x faster.

**Comment by mayasfinest** [comment] 2021-08-27 21:32
And just one question.
Would it be possible to have the On/Off (Bypass) switch of all the Meris pedals also represented as an icon?
As i now control everything completely hands-off the hardware it would be convenient to have the bypass button also on-screen.

**Comment by ElliotGarbus** [comment] 2021-08-27 21:45
It is possible, but outside of the scope of the original design intent.   I've been considering doing a major update, I'll consider that as I start that work.  You could use a midi controller.  

I could create a small standalone program that just toggles the bypass switch.  If you'd like that I could knock that out quickly.

**Comment by mayasfinest** [comment] 2021-08-27 21:59
I solved the stop-at-5 problem.
I did a resave of my already saved preset group. Now everything seems to work flawless.

I wonder why you have left out a on-screen bypass function?
I would find it very useful not to leave the screen and as my 4 Meris pedals are daisy-chained together, they are not silent when the expression pedal is at zero, so i have to bypass them hardwarely if i want to mute them .

Thank you so far for your efforts

**Comment by ElliotGarbus** [comment] 2021-08-27 22:16
Glad to hear it is all working... I'll get an updated release out shortly.

As for the bypass function.  As I was building the editor there were a number of decisions I made about what goes in or not.  The core design is to support preset creation.  I left off capabilities that I did not view as core to that function.  For example the dynamic swell foot switch on the M7, and the bypass.  I view these as performance tools.   I had thought about creating a computer generated LFO to modify any parameter... but left if out, because it was out of scope for the project.  

Part of it also for my personal workflow, that I would bypass the pedals with a midi footswitch or the switch on the pedal while working - so I never felt the need.

**Comment by mayasfinest** [comment] 2021-08-27 22:38
Thanks Elliot, you're such a helpful person and you're doing great software editors that now made these Meris pedals so immensely useful for me. These editors unlock possibilies that otherwise would have been hidden for me.

(I just send you some money via Paypal)

**Comment by ElliotGarbus** [comment] 2021-08-27 22:43
Thanks for the kind words and the donation.  😎

And thanks for reporting the issue!

**Comment by mayasfinest** [comment] 2021-08-27 23:40
Me again ...
OK, in Hedra the update function seems to work, at least it saves a new file but...

- i drag a preset from the library onto a slot
- i change parameters which i then want so save (update)
- right before the window of the Update Preset function appears all changed parameters snap back to where they were before (you can see that on-screen)...
- i am now able to save (update) but the parameters saved were the ones already saved

**Comment by ElliotGarbus** [comment] 2021-08-27 23:56
I am not able to reproduce this behavior.  Try doing a reset on your pedal.  
Just to make sure I am replicating the same action (I'm looking for you to confirm I am doing same actions you are):
1) drag a patch out of the library to preset 1
2) Change a number of parameters
3) press the Update Preset Button, select update.

When I do this - things are behaving as expected.   Have I correctly replicated the steps you are taking?

Note resetting the pedal will restore all factory defaults, so you will need to configure it again.  Also all the presets will revert to the factory presets.

**Comment by mayasfinest** [comment] 2021-08-28 19:09
Yes, that's all correct!

I did a Hedra factory reset and after all things got even more strange, i deleted every residue of your editor on my HD and did a fresh install. That finally did the trick and everything seems to work properly now. I lost some funny generated patches but i haven't tried a lot patch-building so far, so all no problem.

I think there was some kind of file-issue or non matching names... that could be also the reason why my strange rename-workaround finally worked.

I wish i could rename patches in the name tab of the Librarian too (with full-duplex name-change on the pedal) and not only the description . It is rather cumbersome to rename a patch. Possible?

**Comment by ElliotGarbus** [comment] 2021-08-28 20:22
Glad to hear it is all working after a clean start.

_I wish i could rename patches in the name tab of the Librarian too (with full-duplex name-change on the pedal) and not only the description . It is rather cumbersome to rename a patch. Possible?_

I will add your request to the list.  While it it possible to make changes to simplify patch renaming, I don't think this is a feature I will be adding soon.  I am working on how to make sharing patches online easier... but I am at the beginning of what will be a long process. 

Enjoy.
Given the issue is resolved I will be closing this issue.  Please feel free to reach out again with suggestions or issues!
-Elliot

**Closed as completed by ElliotGarbus** 2021-08-28 20:22 UTC
